### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by macmania** [mdn/world-clock#1]
I'm getting an error on my Mac OS X Yosemite computer. I'm trying to build this app so that I can play around with ember and I'm getting an error - 

```
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/j/workspace/web-dev/world-clock/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/j/workspace/web-dev/world-clock/node_modules/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/library.js:133:17
    at setToStringTag (/Users/j/workspace/web-dev/world-clock/node_modules/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/library.js:89:13)
    at /Users/j/workspace/web-dev/world-clock/node_modules/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/library.js:652:3
    at /Users/j/workspace/web-dev/world-clock/node_modules/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/library.js:673:2
    at Object.<anonymous> (/Users/j/workspace/web-dev/world-clock/node_modules/ember-localforage-adapter/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/library.js:2339:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I also changed the package.json to install broccoli-babel-transpiler instead of the essex one - something that the ember build warned me about. I'm pretty new to emberJS and fixing this error would help.

**Comment by holzru** [comment]
Exact same issue
